### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by yingzhige00** [W-qp/MultiSenseSeg#1]
您好。我想复现一遍您的论文，但是我看到您的论文中有对数据集的增强，不知道您能否给一下数据增强的代码，或者给一个您数据增强后的数据集链接。

**Comment by W-qp** [comment]
您指的是什么数据增强呢，随机放缩裁剪那个dataset.py程序里有的，操作对象是tensor。

**Comment by W-qp** [comment]
> 您好。我想复现一遍您的论文，但是我看到您的论文中有对数据集的增强，不知道您能否给一下数据增强的代码，或者给一个您数据增强后的数据集链接。

您指的是什么数据增强呢，随机放缩裁剪那个dataset.py程序里有的，操作对象是tensor。还是您的意思是数据预处理？

**Comment by yingzhige00** [comment]
哦哦哦，抱歉，我以为这个数据集是您提前做好数据预处理的。

**Comment by W-qp** [comment]
> 哦哦哦，抱歉，我以为这个数据集是您提前做好数据预处理的。

预处理和数据增强不是一回事，预处理我记得好像就直接把数据值域统一至[0, 255]再裁剪就行（也可能有别的我忘了，你可以看论文sec.4）；数据增强只用了随机放缩裁剪，那个在dataset.py里，如果模态几何意义ok的话你可以在对应位置加其他数据增强方法例如旋转什么的估计精度能更高点。
