### ISSUE TITLE
数据集的疑问

### ISSUE THREAD

**Issue by jikedream** [W-qp/MultiSenseSeg#2]
您好，我看到您的工作非常出色，想自己复现试试。我用的是ISPRS Vaihingen数据集。我的数据集目录是这个样子的，
|--------------------------------train
          |--------depth
          |--------semseg
          |--------rgb
|---------------------------------val
          |--------depth
          |--------semseg
          |--------rgb
|---------------------------------test
          |--------depth
          |--------semseg
          |--------rgb
我的train.json如下

```json
{
  "1_train_img": "D:/datasets/satellite-dataset/vaihingen/train/rgb/",
  "1_val_img": "D:/datasets/satellite-dataset/vaihingen/val/rgb/",
  "2_train_img": "D:/datasets/satellite-dataset/vaihingen/train/depth/",
  "2_val_img": "D:/datasets/satellite-dataset/vaihingen/val/depth/",

  "train_label": "D:/datasets/satellite-dataset/vaihingen/train/semseg/",
  "val_label": "D:/datasets/satellite-dataset/vaihingen/val/semseg/",

  "runs": "D:/graduate study/MultiSenseSeg-master/runs/train/",
  "classes": "D:/graduate study/MultiSenseSeg-master/json/potsdam_classes.json"
}
```

我的classes.json如下

```json
{
    "impervious surfaces": [255, 255, 255],
    "building": [0, 0, 255],
    "low vegetation": [0, 255, 255],
    "tree": [0, 255, 0],
    "car": [255, 255, 0],
    "background": [255, 0, 0]
}
```

我直接这样跑的话会报错

> Traceback (most recent call last):
>   File "D:\graduate study\MultiSenseSeg-master\train.py", line 225, in <module>
>     train_net(net_type=net_type, net=net, epochs=args.epochs, batch_size=args.batchsize, warm_epochs=args.warm_epochs, lr=args.lr,
>   File "D:\graduate study\MultiSenseSeg-master\train.py", line 105, in train_net
>     masks_pred = net(train_imgs)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\apex-0.1-py3.10.egg\apex\amp\_initialize.py", line 198, in new_fwd
>     output = old_fwd(*applier(args, input_caster),
>   File "D:\graduate study\MultiSenseSeg-master\model\build_model\Build_MultiSenseSeg.py", line 185, in forward
>     x = self.build_MSEs_AMM(x)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Build_multimodal_fuse_head.py", line 81, in forward
>     x_branch = layer(x[i], self.pos[i].to(device=self.device) if self.use_pos else None)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Head_layers.py", line 75, in forward
>     x = self.conv1(x)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
>     input = module(input)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
>     return F.conv2d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead       
>     return F.conv2d(input, weight, bias, self.stride,
> RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead    

我的数据集里面的gt是直接把Vaihingen的真值图进行了裁剪，没有转成灰度图像，想知道是这个的问题吗？

**Comment by W-qp** [comment]
> 您好，我看到您的工作非常出色，想自己复现试试。我用的是ISPRS Vaihingen数据集。我的数据集目录是这个样子的， |--------------------------------train |--------depth |--------semseg |--------rgb |---------------------------------val |--------depth |--------semseg |--------rgb |---------------------------------test |--------depth |--------semseg |--------rgb 我的train.json如下
> 
> ```json
> {
>   "1_train_img": "D:/datasets/satellite-dataset/vaihingen/train/rgb/",
>   "1_val_img": "D:/datasets/satellite-dataset/vaihingen/val/rgb/",
>   "2_train_img": "D:/datasets/satellite-dataset/vaihingen/train/depth/",
>   "2_val_img": "D:/datasets/satellite-dataset/vaihingen/val/depth/",
> 
>   "train_label": "D:/datasets/satellite-dataset/vaihingen/train/semseg/",
>   "val_label": "D:/datasets/satellite-dataset/vaihingen/val/semseg/",
> 
>   "runs": "D:/graduate study/MultiSenseSeg-master/runs/train/",
>   "classes": "D:/graduate study/MultiSenseSeg-master/json/potsdam_classes.json"
> }
> ```
> 
> 我的classes.json如下
> 
> ```json
> {
>     "impervious surfaces": [255, 255, 255],
>     "building": [0, 0, 255],
>     "low vegetation": [0, 255, 255],
>     "tree": [0, 255, 0],
>     "car": [255, 255, 0],
>     "background": [255, 0, 0]
> }
> ```
> 
> 我直接这样跑的话会报错
> 
> > Traceback (most recent call last):
> > File "D:\graduate study\MultiSenseSeg-master\train.py", line 225, in 
> > train_net(net_type=net_type, net=net, epochs=args.epochs, batch_size=args.batchsize, warm_epochs=args.warm_epochs, lr=args.lr,
> > File "D:\graduate study\MultiSenseSeg-master\train.py", line 105, in train_net
> > masks_pred = net(train_imgs)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\apex-0.1-py3.10.egg\apex\amp_initialize.py", line 198, in new_fwd
> > output = old_fwd(*applier(args, input_caster),
> > File "D:\graduate study\MultiSenseSeg-master\model\build_model\Build_MultiSenseSeg.py", line 185, in forward
> > x = self.build_MSEs_AMM(x)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Build_multimodal_fuse_head.py", line 81, in forward
> > x_branch = layer(x[i], self.pos[i].to(device=self.device) if self.use_pos else None)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Head_layers.py", line 75, in forward
> > x = self.conv1(x)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
> > input = module(input)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
> > return self._conv_forward(input, self.weight, self.bias)
> > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
> > return F.conv2d(input, weight, bias, self.stride,
> > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> > return F.conv2d(input, weight, bias, self.stride,
> > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> 
> 我的数据集里面的gt是直接把Vaihingen的真值图进行了裁剪，没有转成灰度图像，想知道是这个的问题吗？

看着应该是第一层卷积通道维度没匹配上，你的depth应该是单通道吧，所以你应该把in_chans改成(3,1)；标签肯定是索引图形式，不能是彩色的

**Comment by jikedream** [comment]
> > 您好，我看到您的工作非常出色，想自己复现试试。我用的是ISPRS Vaihingen数据集。我的数据集目录是这个样子的， |--------------------------------train |--------depth |--------semseg |--------rgb |---------------------------------val |--------depth |--------semseg |--------rgb |---------------------------------test |--------depth |--------semseg |--------rgb 我的train.json如下
> > ```json
> > {
> >   "1_train_img": "D:/datasets/satellite-dataset/vaihingen/train/rgb/",
> >   "1_val_img": "D:/datasets/satellite-dataset/vaihingen/val/rgb/",
> >   "2_train_img": "D:/datasets/satellite-dataset/vaihingen/train/depth/",
> >   "2_val_img": "D:/datasets/satellite-dataset/vaihingen/val/depth/",
> > 
> >   "train_label": "D:/datasets/satellite-dataset/vaihingen/train/semseg/",
> >   "val_label": "D:/datasets/satellite-dataset/vaihingen/val/semseg/",
> > 
> >   "runs": "D:/graduate study/MultiSenseSeg-master/runs/train/",
> >   "classes": "D:/graduate study/MultiSenseSeg-master/json/potsdam_classes.json"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的classes.json如下
> > ```json
> > {
> >     "impervious surfaces": [255, 255, 255],
> >     "building": [0, 0, 255],
> >     "low vegetation": [0, 255, 255],
> >     "tree": [0, 255, 0],
> >     "car": [255, 255, 0],
> >     "background": [255, 0, 0]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我直接这样跑的话会报错
> > > Traceback (most recent call last):
> > > File "D:\graduate study\MultiSenseSeg-master\train.py", line 225, in
> > > train_net(net_type=net_type, net=net, epochs=args.epochs, batch_size=args.batchsize, warm_epochs=args.warm_epochs, lr=args.lr,
> > > File "D:\graduate study\MultiSenseSeg-master\train.py", line 105, in train_net
> > > masks_pred = net(train_imgs)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > return forward_call(*args, **kwargs)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\apex-0.1-py3.10.egg\apex\amp_initialize.py", line 198, in new_fwd
> > > output = old_fwd(*applier(args, input_caster),
> > > File "D:\graduate study\MultiSenseSeg-master\model\build_model\Build_MultiSenseSeg.py", line 185, in forward
> > > x = self.build_MSEs_AMM(x)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > return forward_call(*args, **kwargs)
> > > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Build_multimodal_fuse_head.py", line 81, in forward
> > > x_branch = layer(x[i], self.pos[i].to(device=self.device) if self.use_pos else None)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > return forward_call(*args, **kwargs)
> > > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Head_layers.py", line 75, in forward
> > > x = self.conv1(x)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > return forward_call(*args, **kwargs)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
> > > input = module(input)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > return forward_call(*args, **kwargs)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
> > > return self._conv_forward(input, self.weight, self.bias)
> > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
> > > return F.conv2d(input, weight, bias, self.stride,
> > > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> > > return F.conv2d(input, weight, bias, self.stride,
> > > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> > 
> > 
> > 我的数据集里面的gt是直接把Vaihingen的真值图进行了裁剪，没有转成灰度图像，想知道是这个的问题吗？
> 
> 看着应该是第一层卷积通道维度没匹配上，你的depth应该是单通道吧，所以你应该把in_chans改成(3,1)；标签肯定是索引图形式，不能是彩色的

感谢，复现成功了，感谢您的指导以及您杰出的工作！

**Comment by W-qp** [comment]
> > > 您好，我看到您的工作非常出色，想自己复现试试。我用的是ISPRS Vaihingen数据集。我的数据集目录是这个样子的， |--------------------------------train |--------depth |--------semseg |--------rgb |---------------------------------val |--------depth |--------semseg |--------rgb |---------------------------------test |--------depth |--------semseg |--------rgb 我的train.json如下
> > > ```json
> > > {
> > >   "1_train_img": "D:/datasets/satellite-dataset/vaihingen/train/rgb/",
> > >   "1_val_img": "D:/datasets/satellite-dataset/vaihingen/val/rgb/",
> > >   "2_train_img": "D:/datasets/satellite-dataset/vaihingen/train/depth/",
> > >   "2_val_img": "D:/datasets/satellite-dataset/vaihingen/val/depth/",
> > > 
> > >   "train_label": "D:/datasets/satellite-dataset/vaihingen/train/semseg/",
> > >   "val_label": "D:/datasets/satellite-dataset/vaihingen/val/semseg/",
> > > 
> > >   "runs": "D:/graduate study/MultiSenseSeg-master/runs/train/",
> > >   "classes": "D:/graduate study/MultiSenseSeg-master/json/potsdam_classes.json"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我的classes.json如下
> > > ```json
> > > {
> > >     "impervious surfaces": [255, 255, 255],
> > >     "building": [0, 0, 255],
> > >     "low vegetation": [0, 255, 255],
> > >     "tree": [0, 255, 0],
> > >     "car": [255, 255, 0],
> > >     "background": [255, 0, 0]
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我直接这样跑的话会报错
> > > > Traceback (most recent call last):
> > > > File "D:\graduate study\MultiSenseSeg-master\train.py", line 225, in
> > > > train_net(net_type=net_type, net=net, epochs=args.epochs, batch_size=args.batchsize, warm_epochs=args.warm_epochs, lr=args.lr,
> > > > File "D:\graduate study\MultiSenseSeg-master\train.py", line 105, in train_net
> > > > masks_pred = net(train_imgs)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > > return forward_call(*args, **kwargs)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\apex-0.1-py3.10.egg\apex\amp_initialize.py", line 198, in new_fwd
> > > > output = old_fwd(*applier(args, input_caster),
> > > > File "D:\graduate study\MultiSenseSeg-master\model\build_model\Build_MultiSenseSeg.py", line 185, in forward
> > > > x = self.build_MSEs_AMM(x)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > > return forward_call(*args, **kwargs)
> > > > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Build_multimodal_fuse_head.py", line 81, in forward
> > > > x_branch = layer(x[i], self.pos[i].to(device=self.device) if self.use_pos else None)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > > return forward_call(*args, **kwargs)
> > > > File "D:\graduate study\MultiSenseSeg-master\model\multimodal_fuse\Head_layers.py", line 75, in forward
> > > > x = self.conv1(x)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > > return forward_call(*args, **kwargs)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
> > > > input = module(input)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> > > > return forward_call(*args, **kwargs)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
> > > > return self._conv_forward(input, self.weight, self.bias)
> > > > File "D:\software\conda\envs\yoloworld\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
> > > > return F.conv2d(input, weight, bias, self.stride,
> > > > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> > > > return F.conv2d(input, weight, bias, self.stride,
> > > > RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[8, 1, 512, 512] to have 3 channels, but got 1 channels instead
> > > 
> > > 
> > > 我的数据集里面的gt是直接把Vaihingen的真值图进行了裁剪，没有转成灰度图像，想知道是这个的问题吗？
> > 
> > 
> > 看着应该是第一层卷积通道维度没匹配上，你的depth应该是单通道吧，所以你应该把in_chans改成(3,1)；标签肯定是索引图形式，不能是彩色的
> 
> 感谢，复现成功了，感谢您的指导以及您杰出的工作！

不必客气哈哈
