### ISSUE TITLE
关于DSM模态数据集问题

### ISSUE THREAD

**Issue by HJ-Qin** [W-qp/MultiSenseSeg#4]
看了您的论文，备受启发。有一些问题想请教一下。对于高度模态，您用的是DSM还是nDSM呢。还有高度模态是如何处理送到网络中的呢。

**Comment by HJ-Qin** [comment]
如果可以，您可以分享一下vaihingen数据集吗，因为我从官方下载的vaihingen DSM好像是没有处理过的，只是一张超大的图片。

**Comment by W-qp** [comment]
我并没有用Vaihingen数据集，我用的是Potsdam。时间久了我也有点忘了是DSM还是nDSM，但是应该类似；不管是什么模态，都只需要把它们的像元值域放缩到差不多[0, 255]，然后dataset.py这个里面会将所有的模态按这个值域归一化。ISPRS数据集的预处理我记得只需要将DSM的值域拉伸，然后所有模态使用crop.py对应裁剪为同尺度（最好是2的整数次幂，为了满足多次下采样）的小patch就行。

**Comment by HJ-Qin** [comment]
非常感谢您的回答，让我受益颇深。感谢您做出的杰出贡献。
